apiVersion: batch/v1
kind: Job
metadata:
  name: 120gau
  labels:
    app: 120gau
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: 120gau
    spec:
      volumes:
      - name: data-volume
        hostPath: 
          path: /opt/kubedata
          type: Directory
      containers:
      - name: 120gau
        image: python:3.8-slim
        volumeMounts:
        - name: data-volume
          mountPath: /data
        command: 
        - /bin/sh
        - -c
        - |
          echo v1
          mkdir -p /data/aquatone
          
          cat /data/100.log.txt 
          
          apt update -y
          apt install unzip wget curl -y
          
          wget https://github.com/lc/gau/releases/download/v1.1.0/gau_1.1.0_linux_amd64.tar.gz
          gzip -d gau_1.1.0_linux_amd64.tar.gz
          tar -xvf gau_1.1.0_linux_amd64.tar
          ls -la
          #unzip aquatone_linux_amd64_1.7.0.zip
          echo gau starting...
          
          cat /data/100.log.txt  | ./gau > /data/120.log.txt
          echo all done
          echo new 
          
          


      restartPolicy: Never
